sudo: required
dist: trusty
cache: pip
language: python
python:
- 2.7
install:
- pip install -U pip setuptools pip-tools
- pip install -r dev_requirements.txt
script:
- echo "Hello world, I'll do something real useful.. Real soon!"
deploy:
  provider: pypi
  user: atmosphere
  distributions: sdist bdist_wheel
  password:
    secure: Lt0DdSBYQGxk1kMzbp2HOtkeZ3xV5eiD1E4wGxaPNvVLfMsc8B1Hjumf2QDomS/0kkuXDrmKALrXP7ts7O1gIovIdu6OArjy6edw0yKjaT0JueNPd1+hb71QeZali58K9Wp8JwOhB0qtCAJw5lowDkPGWcwsvnrpOgR5K/Fh1nd+Jr2gLkIY5MS14XCN0DqHzS5rXCSKzIWoFj9TH52uRaVP0DCn/Z20i46VNdxaeeVeg+KsndCKII+BTURDKBKqAK+dZG44WF2ytBNihZP0fh2w88eGaw6w6ALPYdFbQRwObJT3c8tRGpWVyPsL+CnDJrxj5X46jMzBT+7zzfNVdtJaBDwIfyBlqFNSNc6oGp3dOpUMQsxvLbrPEuhUCPzhRoxzj7iucXEY70+vlnlx3uoU+t1UMB/3uEwC+UgGtYQdWz31TApsTBiizw4Pi6dbbdcfrXvYYkKu+YgTMWOESYuzrtumDgxx7ebSL1mypRJNRewN1bjvpoTDlDqLCj5ZpUAp6c8yEUMJ6OfLvnLms1Trc+jl9X4IIzxSs4obj4Y8mHp7h/uqKvy+V0PGqMl9Z6jP6/IwcIZtvsGDi6M6ssaMs2TWpineEo1lOGfOzeuFpuAVVQ2yWDadeI1jgp3dd4XTZ/WxhWA+p6OrwAbuB43cDQyhZIN/bZZnP22x/1s=
  on:
    tags: true
