sudo: required
dist: trusty
cache: pip
language: python
python:
- 2.7
install:
- pip install -U pip setuptools pip-tools
- pip install -r dev_requirements.txt
script:
- echo "Hello world, I'll do something real useful.. Real soon!"
deploy:
  provider: pypi
  user: atmosphere
  distributions: sdist bdist_wheel
  password:
    secure: DPZI45WkXvzk1L3q3tsp2VRTaq88AlW6bWG3h/LeNs3lqfxNXYhxQb0fk6rbrCL06QFTOQP0ybO62hDWQ+SS1HDdgfw6PJ6wxs34vv9enCU3wyHoY9Tfe2Czc4GKDn7dVL6ghWDPzgowWCMnc+DXWzdl/TcwLaB/lKxwA3TfGPNf+QLr30jyrft13IwFVvevyBjCvk/dddKDowGBsjz12ark4RizsQSz5h6OTQg7Uz/kB+nLuSvIa5/YSC4okGZUOdJfdz8pGYjS/RGuLc+/Km8USNjYq96b0PsM6Xj73Hkk83DcN0qryoIZsgdRq+AN6Gk1yaLrr0Lk5erk+ymK6cs+bSwgkrLLxOYK1oaAze8H4pKpSdkG1tLaqii5RvCw3mLINe3Os+amBubEoubguHgQYCpy+Tly1KVymhyO4h4H/JGCujRFQ+QkjPoUDWY8VEa4T3UJ7ytXEvaPgms6081PdnRqu0rchBZMWdnjEuRpH+1bGATeSmVMr0hRu8nBZv34RM7h7ENrtS0E+KV73Wn4L7/363i6/76/chq+vtksHI6z8L/br11vrfy9Dhpv0ydY2CgIQtKx1MdEbc8rXAt5C4uyrlgThD+Bt0oaAOTCcFDjEkBoanKs4GIbfObUFm+dlC6mXkFm8q0lBTmukBHPY9lggMXuSCUdShrKCVs=
  on:
    tags: true
