sudo: required
dist: trusty
cache: pip
language: python
python:
- 2.7
install:
- pip install -U pip setuptools pip-tools
- pip install -r dev_requirements.txt
script:
- echo "Hello world, I'll do something real useful.. Real soon!"
deploy:
  provider: pypi
  user: atmosphere
  distributions: sdist bdist_wheel
  password:
    secure: oEeEifbu6lCmQe1CVTA3/hMitWkx3CLk3gRJjxpD1J8KPO7UheaNbPP/y1NWdR7I1GxYsUm+FUvRPAbp48+ed9N2o6j0dTrdJkTj+8W0OI6C5GReD4cE6tEOBccwprP9kpfDmqVBFmfzjgB2YbMItDh8fKlI/KiZYM9qqCvOdEcxu5fQvfMdTXVsCpG0wMd/qj/rzG6Vr0ExHsw5tk0J28411Abt3XRuLKblLEawXjqyhlT9wz6lxV4pcZpxARVhCGTEXahDqTaaFGVbL8tmSbyzybCxqlcfXW+djx6PnRqlfOS7WAtRVwrq9bmqIilGuX28NI8wutQalP3NVey/7jtlmrNVeF4qggYkLLFxnKOBJBqs2giEnOtGBO/ruSWUqXOqrptDstypug05i+jGJ9lX/Ox8l9kTVRrkrESFQyKAaBo5at3fO+uMwDBp8rda+Y6OVp4fm4NajLvEgOsHV64XFHfrtV1NS+wfqt2BUgi77s8qm8bnfD0+riJbPbqrSg/CZIu6eIrvK1unMxM9HG2m3wOQmYgP6D3zAiGpKmX4Dyrgh3VdlPKCQYKe2D1rTh+ivWDRMDbLX2o6GFl9xttpOy/WaCbn1RMrn2AWsDhYF8SB0sO/PYZPbsN/Gbg+volBS6fkSRRH/W/Yz7iIPkTC/7e3IBjiHmvK98osmKo=
  on:
    tags: true
